name: API in Kotlin using Micronaut

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_URL: ${{ secrets.MYSQL_URL }}
  GITHUB_REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # Specify the JDK distribution
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Compile
        run: ./gradlew assemble

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: build/libs/mysqlrestapi-1.0.0.jar

  test:
    runs-on: ubuntu-24.04
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Test
        run: ./gradlew test --stacktrace
    continue-on-error: true

  code_style:
    runs-on: ubuntu-24.04
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Check Code Style
        run: ./gradlew ktlintKotlinScriptFormat

      - name: Upload ktlint report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: build/ktlint.xml
    continue-on-error: true

  package:
    runs-on: ubuntu-24.04
    needs:
      - test
      - code_style
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Package
        run: ./gradlew shadowJar
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: build/libs/mysqlrestapi-1.0.0.jar

  dockerize:
    runs-on: ubuntu-24.04
    needs: package
    services:
      docker:
        image: docker:24.0.5
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: application
          path: build/libs/mysqlrestapi-1.0.0.jar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mysqlrestapi:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/mysqlrestapi:latest ${{ secrets.DOCKER_USERNAME }}/mysqlrestapi:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mysqlrestapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mysqlrestapi:${{ github.sha }}


  send-to-aws:
    runs-on: ubuntu-24.04
    needs: dockerize
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image from GitHub Container Registry
        run: docker pull ${{ env.GITHUB_REGISTRY }}/mysqlrestapi:latest

      - name: Tag Docker image for AWS ECR
        run: docker tag ${{ env.GITHUB_REGISTRY }}/mysqlrestapi:latest ${{ secrets.AWS_ECR_REGISTRY }}/mysqlrestapi:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ECR_REGISTRY }}/mysqlrestapi:latest




